[build]
builder = "DOCKERFILE"
buildCommand = "docker build -t site2md ."

[deploy]
startCommand = "python -m site2md.web.main --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "8000"
PYTHONUNBUFFERED = "1"